services:
  # .NET Core Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    volumes:
      # Mount SQLite database file so it persists
      - ./data:/app/data
    networks:
      - todo-network

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - todo-network

  # Database Management UI (SQLite Browser)
  db-admin:
    image: coleifer/sqlite-web
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
    networks:
      - todo-network
    depends_on:
      - backend
    command: sqlite_web -H 0.0.0.0 -x /data/ezratask.db

networks:
  todo-network:
    driver: bridge

volumes:
  db-data: