services:
  # .NET Core Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    volumes:
      # Mount SQLite database file so it persists
      - ./data:/app/data
    networks:
      - todo-network

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - todo-network

  # Database Management UI (Adminer)
  db-admin:
    image: adminer:4.8.1
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=sqlite:///data/todos.db
    volumes:
      - ./data:/data
    networks:
      - todo-network
    depends_on:
      - backend

networks:
  todo-network:
    driver: bridge

volumes:
  db-data: